admin_cms:
    path: /
    defaults: { _controller: "FrameworkBundle:Template:template", template: "PositibeCmfBundle::index.html.twig"}


elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

positibe_admin_menu:
    resource: "@PositibeCmfBundle/Resources/config/routing/menu.yml"

positibe_admin_menu_node:
    resource: "@PositibeCmfBundle/Resources/config/routing/menu_node.yml"
#
positibe_admin_menu_node_children:
    resource: "@PositibeCmfBundle/Resources/config/routing/menu_node_children.yml"

positibe_admin_page:
    resource: "@PositibeCmfBundle/Resources/config/routing/page.yml"

positibe_admin_category:
    resource: "@PositibeCmfBundle/Resources/config/routing/category.yml"

positibe_admin_block:
    resource: "@PositibeCmfBundle/Resources/config/routing/block.yml"

positibe_admin_menu_block:
    resource: "@PositibeCmfBundle/Resources/config/routing/menu_block.yml"

positibe_admin_gallery_block:
    resource: "@PositibeCmfBundle/Resources/config/routing/gallery_block.yml"

positibe_admin_content_block:
    resource: "@PositibeCmfBundle/Resources/config/routing/content_block.yml"

positibe_admin_page_block:
    resource: "@PositibeCmfBundle/Resources/config/routing/page_block.yml"